#http://localhost:8080/swagger-ui/index.html
server:
  port: 8080
#  servlet:
#    context-path: /attendance-service
spring:
  application:
    name: user-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:

            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
#            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
#        provider:
#          google:
#            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
#            token-uri: https://www.googleapis.com/oauth2/v4/token
#            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
#            user-name-attribute: sub
#            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
jwt:
  granted: Bearer
  header: Authorization
  secret: asdasd312321312321321e3lk12l3qs;djq2lk4jqwlkejklqw@@ewqke21;l#
  expiration:
    access: 3600000 # 3600 * 1000
    refresh: 86400000 # 3600 * 24 * 1000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

